version: 2.1

jobs:
  # Job one with a unique name
  on_build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          docker build -t myimage .      
      - run:
          docker run -d -p 8080:8080 --name node-sample myimage
      - run:
          name: "test 8080 port"
          command: "docker run --network container:myimage appropriate/curl --retry 10 --retry-connrefused http://localhost:8080"
         

workflows:
  # Name of workflow
  builds:
    # List of jobs that will run
    jobs:
      - on_build